# Generated by Django 4.1 on 2022-08-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'IP Клиента',
                'verbose_name_plural': 'IP Клиентов',
            },
        ),
    ]
