# Generated by Django 4.1 on 2023-01-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='type',
            field=models.CharField(blank=True, choices=[('BT', 'Несоответствие тегам'), ('BM', 'Неподходящие/плохие медиа'), ('PL', 'Плагиат'), ('AN', 'Еще')], max_length=40, verbose_name='тип жалобы'),
        ),
    ]
