# Generated by Django 4.1 on 2023-01-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_complaint_type'),
        ('accounts', '0004_alter_complaint_type_alter_notification_type'),
    ]

    operations = [
    ]
