# Generated by Django 4.1 on 2022-12-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Subscription', 'Subscription'), ('New post', 'New Post'), ('Account', 'Account'), ('Complaint', 'Complaint')], max_length=20, verbose_name='тип уведомления'),
        ),
    ]
