# Generated by Django 4.1 on 2022-12-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_notification_options_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('CN', 'На рассмотрении'), ('AC', 'Принята'), ('RJ', 'Отклонена')], default='CN', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='text',
            field=models.TextField(max_length=200, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SB', 'Подписка'), ('NP', 'Новый пост'), ('AC', 'Аккаунт')], max_length=20, verbose_name='тип уведомления'),
        ),
    ]
