# Generated by Django 4.1 on 2023-01-26 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_description'),
        ('accounts', '0007_alter_postcomplaint_options_postcomplaint_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomplaint',
            old_name='recipient',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SB', 'Подписка'), ('NP', 'Новый пост'), ('AC', 'Аккаунт'), ('CM', 'Комментарий'), ('CP', 'Жалоба')], max_length=10, verbose_name='тип уведомления'),
        ),
        migrations.AlterField(
            model_name='postcomplaint',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='posts.post', verbose_name='пост'),
        ),
    ]
