# Generated by Django 4.1.5 on 2023-03-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_folder_created_alter_folder_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ('-created',), 'verbose_name': 'папка пользователя', 'verbose_name_plural': 'папки пользователей'},
        ),
    ]
