# Generated by Django 4.1.5 on 2023-03-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_folder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='folder',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='иконка'),
        ),
    ]
