# Generated by Django 4.1.5 on 2023-04-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_role_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='color',
            field=models.CharField(default='#fff', help_text='цвет указывается в hex формате', max_length=7, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='role',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='иконка'),
        ),
    ]
