# Generated by Django 4.1.5 on 2023-05-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_role_color_alter_role_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
    ]
