# Generated by Django 4.1.5 on 2023-06-28 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_like_client_ip_alter_like_user'),
        ('accounts', '0023_alter_folder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ignored_tags',
        ),
        migrations.AlterField(
            model_name='postcomplaint',
            name='type',
            field=models.CharField(choices=[('BT', 'Несоответствие тегам'), ('BM', 'Неподходящие/плохие медиа'), ('PL', 'Плагиат'), ('AN', 'Другое')], default='BT', max_length=40, verbose_name='тип жалобы'),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_card_image', models.ImageField(blank=True, null=True, upload_to='users_card_images/')),
                ('notify_on_post_commented', models.BooleanField(default=True, verbose_name='Уведомлять о новом комментарии к посту')),
                ('notify_on_comment_reply', models.BooleanField(default=True, verbose_name='Уведомлять об ответе на комментарий')),
                ('ignored_tags', models.ManyToManyField(blank=True, to='posts.posttag', verbose_name='игнорируемые теги')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
