# Generated by Django 4.1 on 2022-09-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChanelSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название канала')),
                ('url', models.URLField(unique=True, verbose_name='ссылка на доступ к каналу')),
            ],
            options={
                'verbose_name': 'телеграм канал',
                'verbose_name_plural': 'телеграм каналы',
            },
        ),
    ]
