# Generated by Django 4.1 on 2022-11-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcreation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchanelsource',
            name='use_in_generation',
            field=models.BooleanField(default=True, verbose_name='использовать в генерации'),
        ),
    ]
