# Generated by Django 4.1 on 2022-08-20 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TAG_M', 'Несоответствие тегу'), ('AUTHOR_M', 'Несоответствие тегу'), ('BAD_QUALITY', 'Плохое качество'), ('ERROR', 'Ошибка сайта'), ('IRREL_CONTENT', 'Несоответствующий контент')], max_length=20, verbose_name='тип жалобы')),
                ('comment', models.TextField(max_length=200, verbose_name='описание')),
                ('status', models.CharField(choices=[('ADOPTED', 'Принята'), ('REJECTED', 'Отклонена'), ('IS_PENDING', 'В рассмотрении')], default='IS_PENDING', max_length=20, verbose_name='статус')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('url', models.URLField(blank=True, null=True, verbose_name='место ошибки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
    ]
