# Generated by Django 4.1 on 2022-08-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clientip'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='views',
            field=models.ManyToManyField(to='accounts.clientip'),
        ),
        migrations.AddField(
            model_name='textpost',
            name='views',
            field=models.ManyToManyField(to='accounts.clientip'),
        ),
        migrations.AddField(
            model_name='videopost',
            name='views',
            field=models.ManyToManyField(to='accounts.clientip'),
        ),
    ]
