# Generated by Django 4.1 on 2022-08-23 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_clientip'),
        ('posts', '0002_imagepost_views_textpost_views_videopost_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='views',
            field=models.ManyToManyField(blank=True, to='accounts.clientip'),
        ),
        migrations.AlterField(
            model_name='textpost',
            name='views',
            field=models.ManyToManyField(blank=True, to='accounts.clientip'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='views',
            field=models.ManyToManyField(blank=True, to='accounts.clientip'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='imagepost',
            name='likes',
            field=models.ManyToManyField(blank=True, to='posts.like', verbose_name='лайки'),
        ),
        migrations.AddField(
            model_name='textpost',
            name='likes',
            field=models.ManyToManyField(blank=True, to='posts.like', verbose_name='лайки'),
        ),
        migrations.AddField(
            model_name='videopost',
            name='likes',
            field=models.ManyToManyField(blank=True, to='posts.like', verbose_name='лайки'),
        ),
    ]
