# Generated by Django 4.1 on 2023-01-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_views_userview_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PB', 'опубликовано'), ('DF', 'отложено'), ('CN', 'черновик')], default='CN', help_text='При выборе задержки помечается как "отложено"', max_length=20, verbose_name='статус'),
        ),
    ]
