# Generated by Django 4.1 on 2022-08-23 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_imagepost_views_alter_textpost_views_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
