# Generated by Django 4.1 on 2023-01-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='описание'),
        ),
    ]
