# Generated by Django 4.1 on 2022-08-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_delete_mark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AddField(
            model_name='posttag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='название тега'),
        ),
    ]
