# Generated by Django 4.1 on 2022-11-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'опубликованно'), (1, 'отложенно'), (2, 'на рассмотрении')], default=0, verbose_name='статус'),
        ),
    ]
