# Generated by Django 4.1 on 2022-11-23 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_is_published_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='время публикации')),
            ],
            options={
                'verbose_name': 'задержка публикации',
                'verbose_name_plural': 'задержки публикаций',
            },
        ),
        migrations.AlterField(
            model_name='like',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата лайка'),
        ),
        migrations.AlterField(
            model_name='userview',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата просмотра'),
        ),
        migrations.AddField(
            model_name='post',
            name='delay',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='posts.postdelay', verbose_name='задержка'),
        ),
    ]
