# Generated by Django 4.1.5 on 2023-03-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='delay',
        ),
        migrations.AddField(
            model_name='post',
            name='delayed_publication_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отложенной публикации'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.DeleteModel(
            name='PostDelay',
        ),
    ]
