# Generated by Django 4.1 on 2022-11-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postdelay_alter_like_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Опубликованно'), (1, 'Отложено'), (2, 'На рассмотрении')], default=0, help_text='При выборе задержки помечается как "отложено"', verbose_name='статус'),
        ),
    ]
