# Generated by Django 4.1.5 on 2023-03-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_delay_post_delayed_publication_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PB', 'опубликовано'), ('DF', 'отложено'), ('CN', 'черновик')], default='PB', help_text='При выборе задержки помечается как "отложено"', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='posts.posttag', verbose_name='теги'),
        ),
    ]
