# Generated by Django 4.1 on 2022-11-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='delay',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время публикации'),
        ),
        migrations.DeleteModel(
            name='PostDelay',
        ),
    ]
