# Generated by Django 4.1.5 on 2023-04-08 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_alter_folder_is_private'),
        ('posts', '0007_alter_post_status_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='client_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to='accounts.clientip', verbose_name='IP пользователя'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
