# Generated by Django 4.1 on 2022-11-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_delay_delete_postdelay'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='delay',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.postdelay', verbose_name='время отложенной публикации'),
        ),
    ]
