# Generated by Django 4.1 on 2022-11-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_postdelay_alter_post_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdelay',
            name='time',
            field=models.DateTimeField(verbose_name='Время отложенной публикации'),
        ),
    ]
