# Generated by Django 4.1 on 2022-11-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_delay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postdelay',
            options={'verbose_name': 'Отложенная задача', 'verbose_name_plural': 'Отложенные задачи'},
        ),
    ]
