# Generated by Django 4.1 on 2022-11-28 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_postdelay_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 28, 17, 32, 27, 20789, tzinfo=datetime.timezone.utc), verbose_name='дата публикации'),
            preserve_default=False,
        ),
    ]
