# Generated by Django 4.1 on 2022-12-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttag',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
