# Generated by Django 4.1 on 2022-12-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_posttag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='for_premium_users',
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
