# Generated by Django 4.1 on 2022-12-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_remove_post_for_premium_users_alter_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PB', 'опубликовано'), ('DF', 'отложено'), ('CN', 'на рассмотрении')], default='CN', help_text='При выборе задержки помечается как "отложено"', max_length=20, verbose_name='статус'),
        ),
    ]
