# Generated by Django 4.1 on 2022-11-10 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos', verbose_name='файл')),
                ('post', models.ForeignKey(help_text='файл обязательно должен быть прикреплен к посту', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='posts.post')),
            ],
            options={
                'verbose_name': 'Видео файл',
                'verbose_name_plural': 'Видео файлы',
            },
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images', verbose_name='файл')),
                ('use_compression', models.BooleanField(default=False, verbose_name='использовать компрессию')),
                ('compressed', models.BooleanField(default=False)),
                ('post', models.ForeignKey(help_text='файл обязательно должен быть прикреплен к посту', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
