# Generated by Django 4.1 on 2022-08-20 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('accounts', '0001_initial'),
        ('mediacore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='post',
            field=models.ForeignKey(help_text='файл обязательно должен быть прикреплен к посту', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='posts.videopost'),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='content_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contentauthor', verbose_name='автор изображения'),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='post',
            field=models.ForeignKey(help_text='файл обязательно должен быть прикреплен к посту', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='posts.imagepost'),
        ),
    ]
