# Generated by Django 4.1 on 2022-09-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediacore', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefile',
            name='title',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='title',
        ),
    ]
