# Generated by Django 4.1 on 2022-09-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacore', '0003_remove_imagefile_title_remove_videofile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='title',
            field=models.CharField(blank=True, max_length=60, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='title',
            field=models.CharField(blank=True, max_length=60, verbose_name='заголовок'),
        ),
    ]
