# Generated by Django 4.1 on 2022-11-28 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacore', '0004_alter_imagefile_file_alter_videofile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefile',
            name='use_compression',
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='compressed',
            field=models.BooleanField(default=False, verbose_name='Использование компресии'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='file',
            field=models.ImageField(upload_to='post_media/2022_11_28', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png', 'gif'))], verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(upload_to='post_media/2022_11_28', verbose_name='файл'),
        ),
    ]
