# Generated by Django 4.1 on 2022-09-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediacore', '0004_imagefile_title_videofile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefile',
            name='title',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='title',
        ),
    ]
