# Generated by Django 4.1 on 2022-11-29 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacore', '0005_remove_imagefile_use_compression_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='file',
            field=models.ImageField(upload_to='post_media/2022/11/29', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png', 'gif'))], verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(upload_to='post_media/2022/11/29', verbose_name='файл'),
        ),
    ]
