# Generated by Django 4.1.5 on 2023-07-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacore', '0023_videofile_thumbnail_alter_imagefile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
